// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/config": {
            "get": {
                "description": "返回所有服务的访问地址（通过网关和直接地址）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "获取服务配置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ServiceConfigResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.Service": {
            "type": "object",
            "properties": {
                "direct_url": {
                    "description": "直接地址（用于 SDK 内部调用，绕过网关）",
                    "type": "string"
                },
                "path": {
                    "description": "路径前缀",
                    "type": "string"
                },
                "url": {
                    "description": "通过网关的地址",
                    "type": "string"
                }
            }
        },
        "v1.ServiceConfigResponse": {
            "type": "object",
            "properties": {
                "gateway": {
                    "description": "网关地址",
                    "type": "string"
                },
                "services": {
                    "description": "服务配置",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/v1.Service"
                    }
                },
                "version": {
                    "description": "版本",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9090",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AI Agent OS API Gateway",
	Description:      "AI Agent OS API 网关服务文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
