// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Business Source License 1.1",
            "url": "https://github.com/kageos/kageos/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/storage/api/v1/batch_delete": {
            "post": {
                "description": "批量删除某个函数路径下的所有文件（危险操作）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "存储管理"
                ],
                "summary": "删除函数路径下的所有文件",
                "parameters": [
                    {
                        "description": "删除请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteFilesByRouterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteFilesByRouterResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/storage/api/v1/batch_upload_complete": {
            "post": {
                "description": "批量通知后端创建上传记录（仅在上传成功时记录）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "存储管理"
                ],
                "summary": "批量上传完成通知",
                "parameters": [
                    {
                        "description": "批量上传完成请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BatchUploadCompleteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通知成功",
                        "schema": {
                            "$ref": "#/definitions/dto.BatchUploadCompleteResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/storage/api/v1/batch_upload_token": {
            "post": {
                "description": "批量获取多个文件的 presigned_url 上传凭证。如果某个文件未提供 router，将使用默认路由：/{username}/default",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "存储管理"
                ],
                "summary": "批量获取上传凭证",
                "parameters": [
                    {
                        "description": "批量获取上传凭证请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BatchGetUploadTokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.BatchGetUploadTokenResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/storage/api/v1/download/{key}": {
            "get": {
                "description": "重定向到对象存储直连地址，避免服务端转发文件流",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "存储管理"
                ],
                "summary": "下载文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件 Key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件内容",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/storage/api/v1/files": {
            "get": {
                "description": "列举某个函数路径下的所有文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "存储管理"
                ],
                "summary": "列举文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "函数路径",
                        "name": "router",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.ListFilesResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/storage/api/v1/files/description": {
            "post": {
                "description": "更新文件引用对应的描述元数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "存储管理"
                ],
                "summary": "更新文件描述",
                "parameters": [
                    {
                        "description": "更新文件描述请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateFileDescriptionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateFileDescriptionResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/storage/api/v1/files/{key}": {
            "delete": {
                "description": "删除存储的文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "存储管理"
                ],
                "summary": "删除文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件 Key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/storage/api/v1/files/{key}/info": {
            "get": {
                "description": "获取文件的元数据信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "存储管理"
                ],
                "summary": "获取文件信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件 Key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.GetFileInfoResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/storage/api/v1/stats": {
            "get": {
                "description": "获取某个函数路径下的文件数量和总大小",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "存储管理"
                ],
                "summary": "获取存储统计信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "函数路径，例如：luobei/test88888/plugins/cashier_desk",
                        "name": "router",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.GetStorageStatsResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/storage/api/v1/upload_complete": {
            "post": {
                "description": "前端上传完成后，通知后端创建上传记录（仅在上传成功时记录）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "存储管理"
                ],
                "summary": "上传完成通知",
                "parameters": [
                    {
                        "description": "上传完成请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UploadCompleteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通知成功",
                        "schema": {
                            "$ref": "#/definitions/dto.UploadCompleteResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/storage/api/v1/upload_token": {
            "post": {
                "description": "获取文件上传的预签名 URL，文件将按函数路径分类存储。如果未提供 router，将使用默认路由：/{username}/default",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "存储管理"
                ],
                "summary": "获取上传凭证",
                "parameters": [
                    {
                        "description": "获取上传凭证请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GetUploadTokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.GetUploadTokenResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BatchGetUploadTokenReq": {
            "type": "object",
            "required": [
                "files"
            ],
            "properties": {
                "files": {
                    "description": "文件列表（最多100个）",
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/dto.GetUploadTokenReq"
                    }
                },
                "upload_source": {
                    "description": "✨ 上传来源：browser（浏览器）或 server（服务端），默认为 browser",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.UploadSource"
                        }
                    ]
                }
            }
        },
        "dto.BatchGetUploadTokenResp": {
            "type": "object",
            "properties": {
                "tokens": {
                    "description": "上传凭证列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GetUploadTokenResp"
                    }
                }
            }
        },
        "dto.BatchUploadCompleteItem": {
            "type": "object",
            "required": [
                "key"
            ],
            "properties": {
                "bucket": {
                    "description": "存储桶；为空时使用默认桶",
                    "type": "string"
                },
                "content_type": {
                    "description": "✨ 文件类型（上传成功后需要，用于记录）",
                    "type": "string"
                },
                "description": {
                    "description": "文件描述",
                    "type": "string"
                },
                "error": {
                    "description": "错误信息（如果失败）",
                    "type": "string"
                },
                "file_name": {
                    "description": "✨ 文件名（上传成功后需要，用于记录）",
                    "type": "string"
                },
                "file_size": {
                    "description": "✨ 文件大小（上传成功后需要，用于记录）",
                    "type": "integer"
                },
                "hash": {
                    "description": "✨ 文件hash（可选，用于文件标识和 SDK 下载缓存）",
                    "type": "string"
                },
                "key": {
                    "description": "文件 Key",
                    "type": "string"
                },
                "preview_kind": {
                    "description": "预览类型：image/video",
                    "type": "string"
                },
                "router": {
                    "description": "✨ 函数路径（上传成功后需要，用于记录）",
                    "type": "string"
                },
                "success": {
                    "description": "是否成功",
                    "type": "boolean"
                },
                "thumbnail_ref": {
                    "description": "前端生成的缩略图或视频封面文件引用",
                    "type": "string"
                }
            }
        },
        "dto.BatchUploadCompleteReq": {
            "type": "object",
            "required": [
                "items"
            ],
            "properties": {
                "items": {
                    "description": "上传结果列表（最多100个）",
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/dto.BatchUploadCompleteItem"
                    }
                }
            }
        },
        "dto.BatchUploadCompleteResp": {
            "type": "object",
            "properties": {
                "results": {
                    "description": "处理结果列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.BatchUploadCompleteResult"
                    }
                }
            }
        },
        "dto.BatchUploadCompleteResult": {
            "type": "object",
            "properties": {
                "bucket": {
                    "description": "存储桶",
                    "type": "string"
                },
                "description": {
                    "description": "文件描述",
                    "type": "string"
                },
                "download_url": {
                    "description": "✨ 外部访问的下载地址（前端使用）",
                    "type": "string"
                },
                "error": {
                    "description": "错误信息（如果失败）",
                    "type": "string"
                },
                "hash": {
                    "description": "✨ 文件hash（用于 SDK 下载缓存）",
                    "type": "string"
                },
                "key": {
                    "description": "文件 Key",
                    "type": "string"
                },
                "preview_kind": {
                    "description": "预览类型：image/video",
                    "type": "string"
                },
                "ref": {
                    "description": "稳定文件引用：bucket/object_key",
                    "type": "string"
                },
                "server_download_url": {
                    "description": "✨ 内部访问的下载地址（服务端使用）",
                    "type": "string"
                },
                "status": {
                    "description": "状态：completed/failed",
                    "type": "string"
                },
                "thumbnail_ref": {
                    "description": "前端生成的缩略图或视频封面文件引用",
                    "type": "string"
                },
                "thumbnail_url": {
                    "description": "缩略图或视频封面浏览器访问地址",
                    "type": "string"
                }
            }
        },
        "dto.DeleteFilesByRouterReq": {
            "type": "object",
            "required": [
                "router"
            ],
            "properties": {
                "router": {
                    "description": "函数路径",
                    "type": "string"
                }
            }
        },
        "dto.DeleteFilesByRouterResp": {
            "type": "object",
            "properties": {
                "deleted_count": {
                    "type": "integer"
                },
                "router": {
                    "type": "string"
                }
            }
        },
        "dto.GetFileInfoResp": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "etag": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "last_modified": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "dto.GetStorageStatsResp": {
            "type": "object",
            "properties": {
                "file_count": {
                    "type": "integer"
                },
                "router": {
                    "type": "string"
                },
                "size_human": {
                    "description": "人类可读的大小，例如：10.5 MB",
                    "type": "string"
                },
                "total_size": {
                    "type": "integer"
                }
            }
        },
        "dto.GetUploadTokenReq": {
            "type": "object",
            "required": [
                "file_name"
            ],
            "properties": {
                "bucket": {
                    "description": "存储桶；为空时使用 storage 默认桶",
                    "type": "string"
                },
                "content_type": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "hash": {
                    "description": "文件 hash（可选，用于文件标识和 SDK 下载缓存）",
                    "type": "string"
                },
                "preview_for_key": {
                    "description": "原文件 object key；存在时生成与原文件同路径的缩略图/封面 key",
                    "type": "string"
                },
                "router": {
                    "description": "函数路径，例如：luobei/test88888/cashier/cashier_desk.form（可选，未提供时使用默认路由：/{username}/default）",
                    "type": "string"
                },
                "upload_source": {
                    "description": "✨ 上传来源：browser（浏览器）或 server（服务端），默认为 browser",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.UploadSource"
                        }
                    ]
                }
            }
        },
        "dto.GetUploadTokenResp": {
            "type": "object",
            "properties": {
                "bucket": {
                    "description": "存储桶",
                    "type": "string"
                },
                "cdn_domain": {
                    "description": "CDN 域名（可选，用于下载访问）",
                    "type": "string"
                },
                "download_url": {
                    "description": "✨ 预期的下载地址（在获取token时预先构建，上传成功后可直接使用）",
                    "type": "string"
                },
                "expire": {
                    "description": "过期时间",
                    "type": "string"
                },
                "headers": {
                    "description": "请求头",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "key": {
                    "description": "通用字段",
                    "type": "string"
                },
                "method": {
                    "description": "上传方式 ✨ 新增",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.UploadMethod"
                        }
                    ]
                },
                "ref": {
                    "description": "稳定文件引用：bucket/object_key",
                    "type": "string"
                },
                "sdk_config": {
                    "description": "SDK 上传配置（服务端上传时使用；method 仍为 presigned_url）",
                    "type": "object",
                    "additionalProperties": true
                },
                "server_download_url": {
                    "description": "✨ 内部访问的下载地址（服务端/SDK使用）",
                    "type": "string"
                },
                "server_upload_url": {
                    "description": "内部访问的预签名上传地址（服务端/SDK使用）",
                    "type": "string"
                },
                "storage": {
                    "description": "✨ 存储引擎（当前固定为 minio）",
                    "type": "string"
                },
                "upload_domain": {
                    "description": "上传完整域名（例如：http://localhost:9000，用于日志、调试）",
                    "type": "string"
                },
                "upload_host": {
                    "description": "上传域名信息 ✨ 新增",
                    "type": "string"
                },
                "upload_url": {
                    "description": "预签名 URL 上传（当前官方仅 MinIO）",
                    "type": "string"
                },
                "username": {
                    "description": "✨ 当前登录用户的用户名",
                    "type": "string"
                }
            }
        },
        "dto.ListFilesResp": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "router": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateFileDescriptionReq": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "ref": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateFileDescriptionResp": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "ref": {
                    "type": "string"
                }
            }
        },
        "dto.UploadCompleteReq": {
            "type": "object",
            "required": [
                "key"
            ],
            "properties": {
                "bucket": {
                    "description": "存储桶；为空时使用默认桶",
                    "type": "string"
                },
                "content_type": {
                    "description": "✨ 文件类型（上传成功后需要，用于记录）",
                    "type": "string"
                },
                "description": {
                    "description": "文件描述",
                    "type": "string"
                },
                "error": {
                    "description": "错误信息（如果失败）",
                    "type": "string"
                },
                "file_name": {
                    "description": "✨ 文件名（上传成功后需要，用于记录）",
                    "type": "string"
                },
                "file_size": {
                    "description": "✨ 文件大小（上传成功后需要，用于记录）",
                    "type": "integer"
                },
                "hash": {
                    "description": "✨ 文件hash（可选，用于文件标识和 SDK 下载缓存）",
                    "type": "string"
                },
                "key": {
                    "description": "文件 Key",
                    "type": "string"
                },
                "preview_kind": {
                    "description": "预览类型：image/video",
                    "type": "string"
                },
                "router": {
                    "description": "✨ 函数路径（上传成功后需要，用于记录）",
                    "type": "string"
                },
                "success": {
                    "description": "是否成功",
                    "type": "boolean"
                },
                "thumbnail_ref": {
                    "description": "前端生成的缩略图或视频封面文件引用",
                    "type": "string"
                }
            }
        },
        "dto.UploadCompleteResp": {
            "type": "object",
            "properties": {
                "bucket": {
                    "description": "存储桶",
                    "type": "string"
                },
                "content_type": {
                    "description": "文件类型",
                    "type": "string"
                },
                "description": {
                    "description": "文件描述",
                    "type": "string"
                },
                "download_url": {
                    "description": "✨ 外部访问的下载地址（前端使用）",
                    "type": "string"
                },
                "expire": {
                    "description": "过期时间",
                    "type": "string"
                },
                "file_name": {
                    "description": "文件名",
                    "type": "string"
                },
                "file_size": {
                    "description": "文件大小",
                    "type": "integer"
                },
                "hash": {
                    "description": "文件hash",
                    "type": "string"
                },
                "key": {
                    "description": "文件 Key",
                    "type": "string"
                },
                "message": {
                    "description": "消息",
                    "type": "string"
                },
                "preview_kind": {
                    "description": "预览类型：image/video",
                    "type": "string"
                },
                "ref": {
                    "description": "稳定文件引用：bucket/object_key",
                    "type": "string"
                },
                "server_download_url": {
                    "description": "✨ 内部访问的下载地址（服务端使用）",
                    "type": "string"
                },
                "storage": {
                    "description": "存储引擎",
                    "type": "string"
                },
                "thumbnail_ref": {
                    "description": "前端生成的缩略图或视频封面文件引用",
                    "type": "string"
                },
                "thumbnail_url": {
                    "description": "缩略图或视频封面浏览器访问地址",
                    "type": "string"
                }
            }
        },
        "dto.UploadMethod": {
            "type": "string",
            "enum": [
                "presigned_url"
            ],
            "x-enum-comments": {
                "UploadMethodPresignedURL": "预签名 URL（当前官方实际使用）"
            },
            "x-enum-descriptions": [
                "预签名 URL（当前官方实际使用）"
            ],
            "x-enum-varnames": [
                "UploadMethodPresignedURL"
            ]
        },
        "dto.UploadSource": {
            "type": "string",
            "enum": [
                "browser",
                "server"
            ],
            "x-enum-comments": {
                "UploadSourceBrowser": "浏览器上传",
                "UploadSourceServer": "服务端上传（容器内SDK）"
            },
            "x-enum-descriptions": [
                "浏览器上传",
                "服务端上传（容器内SDK）"
            ],
            "x-enum-varnames": [
                "UploadSourceBrowser",
                "UploadSourceServer"
            ]
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9092",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Kageos Storage API",
	Description:      "Kageos 存储服务 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
