// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/agent/agents/create": {
            "post": {
                "description": "创建新的智能体",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "智能体管理"
                ],
                "summary": "创建智能体",
                "parameters": [
                    {
                        "description": "创建智能体请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AgentCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/dto.AgentCreateResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/agents/delete": {
            "post": {
                "description": "删除智能体",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "智能体管理"
                ],
                "summary": "删除智能体",
                "parameters": [
                    {
                        "description": "删除智能体请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AgentDeleteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/agents/disable": {
            "post": {
                "description": "禁用智能体",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "智能体管理"
                ],
                "summary": "禁用智能体",
                "parameters": [
                    {
                        "description": "禁用智能体请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AgentDisableReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "禁用成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/agents/enable": {
            "post": {
                "description": "启用智能体",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "智能体管理"
                ],
                "summary": "启用智能体",
                "parameters": [
                    {
                        "description": "启用智能体请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AgentEnableReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "启用成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/agents/get": {
            "get": {
                "description": "根据ID获取智能体详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "智能体管理"
                ],
                "summary": "获取智能体详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "智能体ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.AgentGetResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/agents/list": {
            "get": {
                "description": "获取所有可用智能体列表（前端调用）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "智能体管理"
                ],
                "summary": "获取智能体列表",
                "parameters": [
                    {
                        "enum": [
                            "knowledge_only",
                            "api_call"
                        ],
                        "type": "string",
                        "description": "智能体类型",
                        "name": "agent_type",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "是否启用",
                        "name": "enabled",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.AgentListResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/agents/update": {
            "post": {
                "description": "更新智能体信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "智能体管理"
                ],
                "summary": "更新智能体",
                "parameters": [
                    {
                        "description": "更新智能体请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AgentUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/dto.AgentUpdateResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/knowledge/add_document": {
            "post": {
                "description": "向知识库添加文档",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库管理"
                ],
                "summary": "添加文档",
                "parameters": [
                    {
                        "description": "添加文档请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.KnowledgeAddDocumentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "添加成功",
                        "schema": {
                            "$ref": "#/definitions/dto.KnowledgeAddDocumentResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/knowledge/create": {
            "post": {
                "description": "创建新的知识库",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库管理"
                ],
                "summary": "创建知识库",
                "parameters": [
                    {
                        "description": "创建知识库请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.KnowledgeCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/dto.KnowledgeCreateResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/knowledge/delete": {
            "post": {
                "description": "删除知识库",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库管理"
                ],
                "summary": "删除知识库",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "知识库ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/knowledge/get": {
            "get": {
                "description": "根据ID获取知识库详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库管理"
                ],
                "summary": "获取知识库详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "知识库ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.KnowledgeGetResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/knowledge/list": {
            "get": {
                "description": "获取所有知识库列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库管理"
                ],
                "summary": "获取知识库列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.KnowledgeListResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/knowledge/list_documents": {
            "get": {
                "description": "获取知识库的文档列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库管理"
                ],
                "summary": "获取文档列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "知识库ID",
                        "name": "knowledge_base_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.KnowledgeListDocumentsResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/knowledge/update": {
            "post": {
                "description": "更新知识库信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库管理"
                ],
                "summary": "更新知识库",
                "parameters": [
                    {
                        "description": "更新知识库请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.KnowledgeUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/dto.KnowledgeUpdateResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/llm/create": {
            "post": {
                "description": "创建新的LLM配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM管理"
                ],
                "summary": "创建LLM配置",
                "parameters": [
                    {
                        "description": "创建LLM配置请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LLMCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/dto.LLMCreateResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/llm/delete": {
            "post": {
                "description": "删除LLM配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM管理"
                ],
                "summary": "删除LLM配置",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "LLM配置ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/llm/get": {
            "get": {
                "description": "根据ID获取LLM配置详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM管理"
                ],
                "summary": "获取LLM配置详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "LLM配置ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.LLMGetResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/llm/get_default": {
            "get": {
                "description": "获取默认的LLM配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM管理"
                ],
                "summary": "获取默认LLM配置",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.LLMGetDefaultResp"
                        }
                    },
                    "400": {
                        "description": "未设置默认配置",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/llm/list": {
            "get": {
                "description": "获取所有LLM配置列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM管理"
                ],
                "summary": "获取LLM配置列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.LLMListResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/llm/set_default": {
            "post": {
                "description": "设置默认的LLM配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM管理"
                ],
                "summary": "设置默认LLM配置",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "LLM配置ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "设置成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/agent/llm/update": {
            "post": {
                "description": "更新LLM配置信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM管理"
                ],
                "summary": "更新LLM配置",
                "parameters": [
                    {
                        "description": "更新LLM配置请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LLMUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/dto.LLMUpdateResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AgentCreateReq": {
            "type": "object",
            "required": [
                "agent_type",
                "chat_type",
                "knowledge_base_id",
                "name"
            ],
            "properties": {
                "agent_type": {
                    "description": "knowledge_only, api_call",
                    "type": "string",
                    "example": "api_call"
                },
                "api_path": {
                    "description": "仅接口调用类型需要",
                    "type": "string",
                    "example": "http://excel-generator:8080/api/v1/process"
                },
                "author": {
                    "type": "string",
                    "example": "beiluo"
                },
                "chat_type": {
                    "type": "string",
                    "example": "chat-task"
                },
                "description": {
                    "type": "string",
                    "example": "基于Excel文件生成管理系统"
                },
                "knowledge_base_id": {
                    "type": "integer",
                    "example": 1
                },
                "metadata": {
                    "type": "string",
                    "example": "{}"
                },
                "name": {
                    "type": "string",
                    "example": "Excel生成智能体"
                },
                "timeout": {
                    "type": "integer",
                    "example": 30
                }
            }
        },
        "dto.AgentCreateResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.AgentDeleteReq": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.AgentDisableReq": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.AgentEnableReq": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.AgentGetResp": {
            "type": "object",
            "properties": {
                "agent_type": {
                    "description": "knowledge_only, api_call",
                    "type": "string",
                    "example": "api_call"
                },
                "api_path": {
                    "type": "string",
                    "example": "http://excel-generator:8080/api/v1/process"
                },
                "author": {
                    "type": "string",
                    "example": "beiluo"
                },
                "chat_type": {
                    "type": "string",
                    "example": "chat-task"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "基于Excel文件生成管理系统"
                },
                "enabled": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "knowledge_base_id": {
                    "type": "integer",
                    "example": 1
                },
                "metadata": {
                    "type": "string",
                    "example": "{}"
                },
                "name": {
                    "type": "string",
                    "example": "Excel生成智能体"
                },
                "timeout": {
                    "type": "integer",
                    "example": 30
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "dto.AgentInfo": {
            "type": "object",
            "properties": {
                "agent_type": {
                    "description": "knowledge_only, api_call",
                    "type": "string",
                    "example": "api_call"
                },
                "api_path": {
                    "type": "string",
                    "example": "http://excel-generator:8080/api/v1/process"
                },
                "author": {
                    "type": "string",
                    "example": "beiluo"
                },
                "chat_type": {
                    "type": "string",
                    "example": "chat-task"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "基于Excel文件生成管理系统"
                },
                "enabled": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "knowledge_base_id": {
                    "type": "integer",
                    "example": 1
                },
                "metadata": {
                    "type": "string",
                    "example": "{}"
                },
                "name": {
                    "type": "string",
                    "example": "Excel生成智能体"
                },
                "timeout": {
                    "type": "integer",
                    "example": 30
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "dto.AgentListResp": {
            "type": "object",
            "properties": {
                "agents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AgentInfo"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "dto.AgentUpdateReq": {
            "type": "object",
            "required": [
                "agent_type",
                "chat_type",
                "id",
                "knowledge_base_id",
                "name"
            ],
            "properties": {
                "agent_type": {
                    "type": "string",
                    "example": "api_call"
                },
                "api_path": {
                    "type": "string",
                    "example": "http://excel-generator:8080/api/v1/process"
                },
                "author": {
                    "type": "string",
                    "example": "beiluo"
                },
                "chat_type": {
                    "type": "string",
                    "example": "chat-task"
                },
                "description": {
                    "type": "string",
                    "example": "基于Excel文件生成管理系统"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "knowledge_base_id": {
                    "type": "integer",
                    "example": 1
                },
                "metadata": {
                    "type": "string",
                    "example": "{}"
                },
                "name": {
                    "type": "string",
                    "example": "Excel生成智能体"
                },
                "timeout": {
                    "type": "integer",
                    "example": 30
                }
            }
        },
        "dto.AgentUpdateResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.DocumentInfo": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "Excel是一个电子表格软件..."
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "doc_id": {
                    "type": "string",
                    "example": "doc_001"
                },
                "file_size": {
                    "type": "integer",
                    "example": 1024
                },
                "file_type": {
                    "type": "string",
                    "example": "pdf"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "knowledge_base_id": {
                    "type": "integer",
                    "example": 1
                },
                "status": {
                    "description": "processing/completed/failed",
                    "type": "string",
                    "example": "completed"
                },
                "title": {
                    "type": "string",
                    "example": "Excel使用指南"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "user": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "dto.KnowledgeAddDocumentReq": {
            "type": "object",
            "required": [
                "content",
                "knowledge_base_id",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "example": "Excel是一个电子表格软件..."
                },
                "file_type": {
                    "description": "pdf/txt/doc/md",
                    "type": "string",
                    "example": "pdf"
                },
                "knowledge_base_id": {
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "example": "Excel使用指南"
                }
            }
        },
        "dto.KnowledgeAddDocumentResp": {
            "type": "object",
            "properties": {
                "doc_id": {
                    "type": "string",
                    "example": "doc_001"
                }
            }
        },
        "dto.KnowledgeCreateReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Excel相关的知识库"
                },
                "name": {
                    "type": "string",
                    "example": "Excel知识库"
                },
                "status": {
                    "description": "active/inactive",
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "dto.KnowledgeCreateResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.KnowledgeGetResp": {
            "type": "object",
            "properties": {
                "content_hash": {
                    "type": "string",
                    "example": "abc123..."
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Excel相关的知识库"
                },
                "document_count": {
                    "type": "integer",
                    "example": 10
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Excel知识库"
                },
                "status": {
                    "description": "active/inactive",
                    "type": "string",
                    "example": "active"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "user": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "dto.KnowledgeInfo": {
            "type": "object",
            "properties": {
                "content_hash": {
                    "type": "string",
                    "example": "abc123..."
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Excel相关的知识库"
                },
                "document_count": {
                    "type": "integer",
                    "example": 10
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Excel知识库"
                },
                "status": {
                    "description": "active/inactive",
                    "type": "string",
                    "example": "active"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "user": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "dto.KnowledgeListDocumentsResp": {
            "type": "object",
            "properties": {
                "documents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DocumentInfo"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "dto.KnowledgeListResp": {
            "type": "object",
            "properties": {
                "knowledge_bases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.KnowledgeInfo"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "dto.KnowledgeUpdateReq": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Excel相关的知识库"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Excel知识库"
                },
                "status": {
                    "description": "active/inactive",
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "dto.KnowledgeUpdateResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.LLMCreateReq": {
            "type": "object",
            "required": [
                "model",
                "name",
                "provider"
            ],
            "properties": {
                "api_base": {
                    "type": "string",
                    "example": "https://api.openai.com/v1"
                },
                "api_key": {
                    "type": "string",
                    "example": "sk-xxx"
                },
                "extra_config": {
                    "type": "string",
                    "example": "{}"
                },
                "is_default": {
                    "type": "boolean",
                    "example": false
                },
                "max_tokens": {
                    "type": "integer",
                    "example": 4000
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4"
                },
                "name": {
                    "type": "string",
                    "example": "OpenAI GPT-4"
                },
                "provider": {
                    "type": "string",
                    "example": "openai"
                },
                "timeout": {
                    "type": "integer",
                    "example": 120
                }
            }
        },
        "dto.LLMCreateResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.LLMGetDefaultResp": {
            "type": "object",
            "properties": {
                "api_base": {
                    "type": "string",
                    "example": "https://api.openai.com/v1"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "extra_config": {
                    "type": "string",
                    "example": "{}"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_default": {
                    "type": "boolean",
                    "example": true
                },
                "max_tokens": {
                    "type": "integer",
                    "example": 4000
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4"
                },
                "name": {
                    "type": "string",
                    "example": "OpenAI GPT-4"
                },
                "provider": {
                    "description": "openai, claude, local, etc.",
                    "type": "string",
                    "example": "openai"
                },
                "timeout": {
                    "type": "integer",
                    "example": 120
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "dto.LLMGetResp": {
            "type": "object",
            "properties": {
                "api_base": {
                    "type": "string",
                    "example": "https://api.openai.com/v1"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "extra_config": {
                    "type": "string",
                    "example": "{}"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_default": {
                    "type": "boolean",
                    "example": true
                },
                "max_tokens": {
                    "type": "integer",
                    "example": 4000
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4"
                },
                "name": {
                    "type": "string",
                    "example": "OpenAI GPT-4"
                },
                "provider": {
                    "description": "openai, claude, local, etc.",
                    "type": "string",
                    "example": "openai"
                },
                "timeout": {
                    "type": "integer",
                    "example": 120
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "dto.LLMInfo": {
            "type": "object",
            "properties": {
                "api_base": {
                    "type": "string",
                    "example": "https://api.openai.com/v1"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "extra_config": {
                    "type": "string",
                    "example": "{}"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_default": {
                    "type": "boolean",
                    "example": true
                },
                "max_tokens": {
                    "type": "integer",
                    "example": 4000
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4"
                },
                "name": {
                    "type": "string",
                    "example": "OpenAI GPT-4"
                },
                "provider": {
                    "description": "openai, claude, local, etc.",
                    "type": "string",
                    "example": "openai"
                },
                "timeout": {
                    "type": "integer",
                    "example": 120
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "dto.LLMListResp": {
            "type": "object",
            "properties": {
                "configs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.LLMInfo"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "dto.LLMUpdateReq": {
            "type": "object",
            "required": [
                "id",
                "model",
                "name",
                "provider"
            ],
            "properties": {
                "api_base": {
                    "type": "string",
                    "example": "https://api.openai.com/v1"
                },
                "api_key": {
                    "type": "string",
                    "example": "sk-xxx"
                },
                "extra_config": {
                    "type": "string",
                    "example": "{}"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_default": {
                    "type": "boolean",
                    "example": false
                },
                "max_tokens": {
                    "type": "integer",
                    "example": 4000
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4"
                },
                "name": {
                    "type": "string",
                    "example": "OpenAI GPT-4"
                },
                "provider": {
                    "type": "string",
                    "example": "openai"
                },
                "timeout": {
                    "type": "integer",
                    "example": 120
                }
            }
        },
        "dto.LLMUpdateResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-Token",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9095",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Agent-Server API",
	Description:      "Agent-Server 代码生成服务 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
