// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agent/api/v1/llm/create": {
            "post": {
                "description": "创建新的LLM配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM管理"
                ],
                "summary": "创建LLM配置",
                "parameters": [
                    {
                        "description": "创建LLM配置请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LLMCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/dto.LLMCreateResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/agent/api/v1/llm/delete": {
            "post": {
                "description": "删除LLM配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM管理"
                ],
                "summary": "删除LLM配置",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "LLM配置ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/agent/api/v1/llm/get": {
            "get": {
                "description": "根据ID获取LLM配置详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM管理"
                ],
                "summary": "获取LLM配置详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "LLM配置ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.LLMGetResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/agent/api/v1/llm/get_default": {
            "get": {
                "description": "获取默认的LLM配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM管理"
                ],
                "summary": "获取默认LLM配置",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.LLMGetDefaultResp"
                        }
                    },
                    "400": {
                        "description": "未设置默认配置",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/agent/api/v1/llm/list": {
            "get": {
                "description": "获取所有LLM配置列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM管理"
                ],
                "summary": "获取LLM配置列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/dto.LLMListResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/agent/api/v1/llm/set_default": {
            "post": {
                "description": "设置默认的LLM配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM管理"
                ],
                "summary": "设置默认LLM配置",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "LLM配置ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "设置成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/agent/api/v1/llm/update": {
            "post": {
                "description": "更新LLM配置信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM管理"
                ],
                "summary": "更新LLM配置",
                "parameters": [
                    {
                        "description": "更新LLM配置请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LLMUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/dto.LLMUpdateResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.LLMCreateReq": {
            "type": "object",
            "required": [
                "model",
                "name",
                "provider"
            ],
            "properties": {
                "admin": {
                    "description": "管理员列表（逗号分隔，默认创建用户）",
                    "type": "string",
                    "example": "user1,user2"
                },
                "api_base": {
                    "type": "string",
                    "example": "https://api.openai.com/v1"
                },
                "api_key": {
                    "type": "string",
                    "example": "sk-xxx"
                },
                "extra_config": {
                    "type": "string",
                    "example": "{}"
                },
                "is_default": {
                    "type": "boolean",
                    "example": false
                },
                "max_tokens": {
                    "type": "integer",
                    "example": 8196
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4"
                },
                "name": {
                    "type": "string",
                    "example": "OpenAI GPT-4"
                },
                "provider": {
                    "type": "string",
                    "example": "openai"
                },
                "timeout": {
                    "type": "integer",
                    "example": 300
                },
                "use_thinking": {
                    "description": "是否使用思考模式（GLM特有功能）",
                    "type": "boolean",
                    "example": false
                },
                "visibility": {
                    "description": "0: 公开, 1: 私有（默认0）",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "dto.LLMCreateResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dto.LLMGetDefaultResp": {
            "type": "object",
            "properties": {
                "admin": {
                    "description": "管理员列表（逗号分隔）",
                    "type": "string",
                    "example": "user1,user2"
                },
                "api_base": {
                    "type": "string",
                    "example": "https://api.openai.com/v1"
                },
                "api_key": {
                    "type": "string",
                    "example": "sk-xxx"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "extra_config": {
                    "type": "string",
                    "example": "{}"
                },
                "has_api_key": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_admin": {
                    "description": "当前用户是否是管理员",
                    "type": "boolean",
                    "example": true
                },
                "is_default": {
                    "type": "boolean",
                    "example": true
                },
                "max_tokens": {
                    "type": "integer",
                    "example": 8196
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4"
                },
                "name": {
                    "type": "string",
                    "example": "OpenAI GPT-4"
                },
                "provider": {
                    "description": "openai, claude, local, etc.",
                    "type": "string",
                    "example": "openai"
                },
                "timeout": {
                    "type": "integer",
                    "example": 300
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "use_thinking": {
                    "description": "是否使用思考模式（GLM特有功能）",
                    "type": "boolean",
                    "example": false
                },
                "visibility": {
                    "description": "0: 公开, 1: 私有",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "dto.LLMGetResp": {
            "type": "object",
            "properties": {
                "admin": {
                    "description": "管理员列表（逗号分隔）",
                    "type": "string",
                    "example": "user1,user2"
                },
                "api_base": {
                    "type": "string",
                    "example": "https://api.openai.com/v1"
                },
                "api_key": {
                    "type": "string",
                    "example": "sk-xxx"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "extra_config": {
                    "type": "string",
                    "example": "{}"
                },
                "has_api_key": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_admin": {
                    "description": "当前用户是否是管理员",
                    "type": "boolean",
                    "example": true
                },
                "is_default": {
                    "type": "boolean",
                    "example": true
                },
                "max_tokens": {
                    "type": "integer",
                    "example": 8196
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4"
                },
                "name": {
                    "type": "string",
                    "example": "OpenAI GPT-4"
                },
                "provider": {
                    "description": "openai, claude, local, etc.",
                    "type": "string",
                    "example": "openai"
                },
                "timeout": {
                    "type": "integer",
                    "example": 300
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "use_thinking": {
                    "description": "是否使用思考模式（GLM特有功能）",
                    "type": "boolean",
                    "example": false
                },
                "visibility": {
                    "description": "0: 公开, 1: 私有",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "dto.LLMInfo": {
            "type": "object",
            "properties": {
                "admin": {
                    "description": "管理员列表（逗号分隔）",
                    "type": "string",
                    "example": "user1,user2"
                },
                "api_base": {
                    "type": "string",
                    "example": "https://api.openai.com/v1"
                },
                "api_key": {
                    "type": "string",
                    "example": "sk-xxx"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "extra_config": {
                    "type": "string",
                    "example": "{}"
                },
                "has_api_key": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_admin": {
                    "description": "当前用户是否是管理员",
                    "type": "boolean",
                    "example": true
                },
                "is_default": {
                    "type": "boolean",
                    "example": true
                },
                "max_tokens": {
                    "type": "integer",
                    "example": 8196
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4"
                },
                "name": {
                    "type": "string",
                    "example": "OpenAI GPT-4"
                },
                "provider": {
                    "description": "openai, claude, local, etc.",
                    "type": "string",
                    "example": "openai"
                },
                "timeout": {
                    "type": "integer",
                    "example": 300
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "use_thinking": {
                    "description": "是否使用思考模式（GLM特有功能）",
                    "type": "boolean",
                    "example": false
                },
                "visibility": {
                    "description": "0: 公开, 1: 私有",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "dto.LLMListResp": {
            "type": "object",
            "properties": {
                "configs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.LLMInfo"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "dto.LLMUpdateReq": {
            "type": "object",
            "required": [
                "id",
                "model",
                "name",
                "provider"
            ],
            "properties": {
                "admin": {
                    "description": "管理员列表（逗号分隔）",
                    "type": "string",
                    "example": "user1,user2"
                },
                "api_base": {
                    "type": "string",
                    "example": "https://api.openai.com/v1"
                },
                "api_key": {
                    "type": "string",
                    "example": "sk-xxx"
                },
                "extra_config": {
                    "type": "string",
                    "example": "{}"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_default": {
                    "type": "boolean",
                    "example": false
                },
                "max_tokens": {
                    "type": "integer",
                    "example": 8196
                },
                "model": {
                    "type": "string",
                    "example": "gpt-4"
                },
                "name": {
                    "type": "string",
                    "example": "OpenAI GPT-4"
                },
                "provider": {
                    "type": "string",
                    "example": "openai"
                },
                "timeout": {
                    "type": "integer",
                    "example": 300
                },
                "use_thinking": {
                    "description": "是否使用思考模式（GLM特有功能）",
                    "type": "boolean",
                    "example": false
                },
                "visibility": {
                    "description": "0: 公开, 1: 私有",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "dto.LLMUpdateResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-Token",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9095",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Agent-Server API",
	Description:      "Agent-Server 代码生成服务 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
