export { useAuthStore } from '@/architecture/infrastructure/stores/auth'
export { useDepartmentInfoStore } from '@/architecture/infrastructure/stores/departmentInfo'
export { useLocaleStore } from '@/architecture/infrastructure/stores/locale'
export { useThemeStore } from '@/architecture/infrastructure/stores/theme'
export { useUserInfoStore } from '@/architecture/infrastructure/stores/userInfo'
