server:
  port: 9095
  listen_host: "127.0.0.1"
  log_level: "info"
  debug: false
  enable_pprof: false

db:
  type: "mysql"
  host: "${MYSQL_HOST}"
  port: ${MYSQL_PORT}
  user: "root"
  password: "${MYSQL_ROOT_PASSWORD}"
  name: "agent-server"
  max_idle_conns: 10
  max_open_conns: 100
  max_lifetime: 300
  log_level: "info"
  slow_threshold: 200
