server:
  port: 9097
  log_level: "info"
  debug: false

db:
  type: "mysql"
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "${MYSQL_ROOT_PASSWORD}"
  name: "hr-server"
  max_idle_conns: 10
  max_open_conns: 100
  max_lifetime: 300
  log_level: "warn"
  slow_threshold: 200

email:
  smtp:
    host: "${SMTP_HOST}"
    port: ${SMTP_PORT}
    username: "${SMTP_USERNAME}"
    password: "${SMTP_PASSWORD}"
    from: "${SMTP_FROM}"
    from_name: "${SMTP_FROM_NAME}"
  verification:
    code_length: 6
    code_expire: 300
