server:
  port: 9095
  log_level: "info"
  debug: false

db:
  type: "mysql"
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "__MYSQL_ROOT_PASSWORD__"
  name: "agent-server"
  max_idle_conns: 10
  max_open_conns: 100
  max_lifetime: 300
  log_level: "info"
  slow_threshold: 200

agent:
  timeout: 30
