server:
  port: 9097
  log_level: "info"
  debug: false

db:
  type: "mysql"
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "__MYSQL_ROOT_PASSWORD__"
  name: "hr-server"
  max_idle_conns: 10
  max_open_conns: 100
  max_lifetime: 300
  log_level: "warn"
  slow_threshold: 200

email:
  smtp:
    host: "__SMTP_HOST__"
    port: __SMTP_PORT__
    username: "__SMTP_USERNAME__"
    password: "__SMTP_PASSWORD__"
    from: "__SMTP_FROM__"
    from_name: "__SMTP_FROM_NAME__"
  verification:
    code_length: 6
    code_expire: 300
